//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int event_id { get; set; }
        public string event_name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string desc { get; set; }
        public string notes { get; set; }
        public string dress_code { get; set; }
        public Nullable<bool> off_campus { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
    
        public virtual signup signup { get; set; }
    }
}
