//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class signup
    {
        [DisplayName ("Event ID")]
        public int event_id { get; set; }

        [DisplayName ("UID")]
        public int student_id { get; set; }

        [DisplayName ("First Name")]
        public string fname { get; set; }

        [DisplayName ("Last Name")]
        public string lname { get; set; }

        [DisplayName ("Major")]
        public string major { get; set; }

        [DisplayName ("EagleMail")]
        public string email { get; set; }
    }
}
